####  __Autores__: 
####  - González Díaz, Guillermo
  
####  - Sebastiani, Carlos

In [2]:
# Librerias
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
import datetime
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

#Librarias de modelos
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.pipeline import Pipeline

In [3]:
##Enconders
import category_encoders as ce
from sklearn.preprocessing import OneHotEncoder

In [4]:
#Configuración de visualización de notebook
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 500)

In [9]:
#Cargamos la data
data = pd.read_csv('../data/NCDB_1999_to_2014.csv')

In [10]:
#Cambiamos los nombres de las columnas para pasarlas a minúscula
data.columns= data.columns.str.lower()

In [11]:
#Hacemos un check para ver que esté bien cargado
data.head()

,c_year,c_mnth,c_wday,c_hour,c_sev,c_vehs,c_conf,c_rcfg,c_wthr,c_rsur,c_raln,c_traf,v_id,v_type,v_year,p_id,p_sex,p_age,p_psn,p_isev,p_safe,p_user
0,1999,1,1,20,2,02,34,UU,1,5,3,03,01,06,1990,01,M,41,11,1,UU,1
1,1999,1,1,20,2,02,34,UU,1,5,3,03,02,01,1987,01,M,19,11,1,UU,1
2,1999,1,1,20,2,02,34,UU,1,5,3,03,02,01,1987,02,F,20,13,2,02,2
3,1999,1,1,08,2,01,01,UU,5,3,6,18,01,01,1986,01,M,46,11,1,UU,1
4,1999,1,1,08,2,01,01,UU,5,3,6,18,99,NN,NNNN,01,M,05,99,2,UU,3

In [12]:
#Elmiminamos duplicados y comprobamos las dimensiones del data_set
print(data.shape, data.drop_duplicates().shape)
data=data.drop_duplicates()

(5860405, 22) (5855336, 22)

In [13]:
# Primero definimos una nueva columna: accidente mortal, que tomará 1s o 0s y contamos cuantos 1 hay (muertos). 
data['acc_mortal'] = data['c_sev'] == 1
data["acc_mortal"] = data["acc_mortal"].astype(int)
data.acc_mortal.sum()

98616

### Variables Missings

In [14]:
#Vemos la cantidad de nulos que tenemos en la data. 
pd_series_null_columns = data.isnull().sum().sort_values(ascending=False)
pd_null_columnas = pd.DataFrame(pd_series_null_columns, columns=['nulos_columnas'])     
pd_null_columnas['porcentaje_columnas'] = pd_null_columnas['nulos_columnas']/data.shape[0]
pd_null_columnas

            nulos_columnas  porcentaje_columnas
c_vehs                   3         5.123532e-07
c_year                   0         0.000000e+00
v_id                     0         0.000000e+00
p_user                   0         0.000000e+00
p_safe                   0         0.000000e+00
p_isev                   0         0.000000e+00
p_psn                    0         0.000000e+00
p_age                    0         0.000000e+00
p_sex                    0         0.000000e+00
p_id                     0         0.000000e+00
v_year                   0         0.000000e+00
v_type                   0         0.000000e+00
c_traf                   0         0.000000e+00
c_mnth                   0         0.000000e+00
c_raln                   0         0.000000e+00
c_rsur                   0         0.000000e+00
c_wthr                   0         0.000000e+00
c_rcfg                   0         0.000000e+00
c_conf                   0         0.000000e+00
c_sev                    0         0.000000e+00
c_hour                   0         0.000000e+00
c_wday                   0         0.000000e+00
acc_mortal               0         0.000000e+00

In [15]:
#En vista de que son muy pocos, nos lo quitamos de primeras
data=data.dropna()

En nuestro dataset, hay unos valores que son **Xs o Us, según nuestra data, estos son los valores nulos**. Las U's son datos 'Unknown' y las Xs son datos que la administración no nos entrega. Por lo tanto para poder hacer una correcta valoración acerca de los valores nulos contaremos todos los que hay en este formato.

In [16]:
# Creamos un loop para contar cuantos 'U's y 'X's hay

missings_u_per_columns=[]
missings_x_per_columns=[]
percentage_of_missing_u=[]
percentage_of_missing_x=[]
total_missing =[]
percentage_of_missing_total=[]
for i in data.columns:
    
    num_of_missing_u= sum(data[i]=='U')+ +sum(data[i]=='UU')+sum(data[i]=='UUUU')
    num_of_missing_x= sum(data[i]=='X')+sum(data[i]=='XX')+sum(data[i]=='XXXX')
    pct_of_missing_u= (num_of_missing_u / len(data))*100
    pct_of_missing_x=(num_of_missing_x / len(data))*100
    num_of_missing_t=num_of_missing_u+num_of_missing_x
    pct_of_missing_total=((num_of_missing_u+num_of_missing_x) / len(data))*100
    
    missings_u_per_columns.append(num_of_missing_u)
    missings_x_per_columns.append(num_of_missing_x)
    percentage_of_missing_u.append(pct_of_missing_u)
    percentage_of_missing_x.append(pct_of_missing_x)
    total_missing.append(num_of_missing_t)
    percentage_of_missing_total.append(pct_of_missing_total)

In [17]:
#creamos el data frame para poder visualizar los valores 'U' y 'X'
missings = pd.DataFrame()
missings['colnames']= data.columns

missings['missing_u']= missings_u_per_columns
missings['pct_of_missing_u']= percentage_of_missing_u
missings['missing_x']= missings_x_per_columns
missings['pct_of_missing_x']= percentage_of_missing_x
missings['total_missing']= total_missing
missings['pct_of_missing_total']= percentage_of_missing_total

missings= missings.set_index('colnames')

missings.sort_values('pct_of_missing_total', ascending=False)

,missing_u,pct_of_missing_u,missing_x,pct_of_missing_x,total_missing,pct_of_missing_total
colnames,,,,,,
p_safe,614507,10.494826,0,0.0,614507,10.494826
c_rcfg,504546,8.616863,0,0.0,504546,8.616863
c_raln,434626,7.422738,0,0.0,434626,7.422738
p_age,376225,6.425339,0,0.0,376225,6.425339
v_year,323296,5.521394,0,0.0,323296,5.521394
p_sex,234351,4.002351,0,0.0,234351,4.002351
c_traf,223448,3.816145,0,0.0,223448,3.816145
c_conf,178785,3.053370,0,0.0,178785,3.053370
p_user,175455,2.996499,0,0.0,175455,2.996499
c_wthr,87953,1.502101,0,0.0,87953,1.502101
p_isev,80665,1.377633,0,0.0,80665,1.377633
c_rsur,78433,1.339514,0,0.0,78433,1.339514
c_hour,59404,1.014528,0,0.0,59404,1.014528
p_psn,57633,0.984282,0,0.0,57633,0.984282
v_type,29720,0.507571,0,0.0,29720,0.507571
c_wday,1323,0.022595,0,0.0,1323,0.022595
c_vehs,541,0.009239,0,0.0,541,0.009239
v_id,433,0.007395,0,0.0,433,0.007395
c_mnth,385,0.006575,0,0.0,385,0.006575
p_id,16,0.000273,0,0.0,16,0.000273
c_year,0,0.000000,0,0.0,0,0.000000
c_sev,0,0.000000,0,0.0,0,0.000000
acc_mortal,0,0.000000,0,0.0,0,0.000000

Vemos que no existen valores Xs, todos los demás son valores unknow.

Para estos valores missing, en vista de que son variables categóricas, los dejaremos por ahora en el dataset. 

Algunas de las variables que tienen más valores missings son p_safe o c_rcfg

En principio estas parecen variables importantes para la predicción recordemos que por ejemplo p_safe es si los afectados estaban utlizando algún dispositivo de seguridad o no (como un casco o ropa reflectante). En el caso de

### Variables Dummies en el Dataset

**Hay otros datos que son Ns** que también valdría la pena explorar. 

Estos datos son los que han sido creados debido a que en nuestro dataset no deberían aparecer. 

Por ejemplo, la variable v_year que es el año del vehículo, si en el accidente que ha habido era una bicicleta o un peaton, esta variable debería ser NNNN,a que no hay vehículo y por lo tanto tampoco hay año del vehículo.

In [19]:
## Missing dummies
missings_n_per_columns=[]
missings_q_per_columns=[]
percentage_of_missing_n=[]
percentage_of_missing_q=[]
total_missing =[]
percentage_of_missing_total=[]
for i in data.columns:
    
    num_of_missing_q= sum(data[i]=='Q')+ +sum(data[i]=='QQ')+sum(data[i]=='QQQQ')
    num_of_missing_n= sum(data[i]=='N')+sum(data[i]=='NN')+sum(data[i]=='NNNN')
    pct_of_missing_q= (num_of_missing_q / len(data))*100
    pct_of_missing_n=(num_of_missing_n / len(data))*100
    num_of_missing_t=num_of_missing_q+num_of_missing_n
    pct_of_missing_total=((num_of_missing_q+num_of_missing_n) / len(data))*100
    
    missings_q_per_columns.append(num_of_missing_q)
    missings_n_per_columns.append(num_of_missing_n)
    percentage_of_missing_q.append(pct_of_missing_q)
    percentage_of_missing_n.append(pct_of_missing_n)
    total_missing.append(num_of_missing_t)
    percentage_of_missing_total.append(pct_of_missing_total)

In [20]:
#Creamos data frame para visualizar QQ, y NN
missings = pd.DataFrame()
missings['colnames']= data.columns

missings['missing_q']= missings_q_per_columns
missings['pct_of_missing_q']= percentage_of_missing_q
missings['missing_n']= missings_n_per_columns
missings['pct_of_missing_n']= percentage_of_missing_n
missings['total_missing']= total_missing
missings['pct_of_missing_total']= percentage_of_missing_total

missings= missings.set_index('colnames')

missings.sort_values('pct_of_missing_total', ascending=False).head()

,missing_q,pct_of_missing_q,missing_n,pct_of_missing_n,total_missing,pct_of_missing_total
colnames,,,,,,
p_safe,47085,0.804139,571398,9.758591,618483,10.562730
p_isev,0,0.000000,290628,4.963475,290628,4.963475
c_conf,284939,4.866316,0,0.000000,284939,4.866316
v_year,0,0.000000,259879,4.438330,259879,4.438330
v_type,25395,0.433707,227548,3.886167,252943,4.319874

Vemos que hay variables dummies, en la mayoría de los casos las utilizaremos como variables categóricas igual que los unknown

Lo único que vamos a cambiar es para la variable v_year. Esta variable queremos que sea numérica por lo tanto haremos la siguiente transformación:

- Cambiaremos los NNs por -99 para que se alejen de valores normales de los años del vehículo y sean faciles de identificar. 
- Cambiaremos los Us, y los Xs por 0 para que sean faciles de identificar de igual manera.

In [21]:
#Cambiamos los NNNN, los UUUU y lox XXXX de la columna v_year para poder transformarla a int. les ponemos valores dummies
#alejados de los valores normales
data['v_year']=data['v_year'].replace('NNNN',-99)
data['v_year']=data['v_year'].replace('UUUU',0)
data['v_year']=data['v_year'].replace('XXXX',0)

### Cambio de formato de Data, debido a repetidos

A veces, nuestr data tiene por ejemplo valores "01" y valores 1. Esto, evidentemente son el mismo dato, pero como utilizaremos variables categóricas, parecen dos distintas. A continuación realizaremos las transfromaciones necesarias para que las variables que tienen estos problemas queden iguales y sin duplicadas

In [25]:
#Vamos a crear un diccionario para poder cambiarlos

# Lista con los numeros str con formato '01','02'.'03'...
categories_00_format=['%.2d' % i for i in range(100)]
categories_00_format

#Esta segunda lista son números normales de 1 al 99 en formato int
mumbers_0_format=[i for i in range(100)]
mumbers_0_format

#Unimos las dos listas anteriores
categories_00_format.extend(mumbers_0_format)

#Esta tercera lista son numeros como string con formato normal que son con los que quiero terminar 
categories0_format=list([str(i) for i in range(100)])
categories0_format.extend(list([str(i) for i in range(100)]))


#Las unimos en un diccionario
zip_iterator = zip(categories_00_format, categories0_format)
diccionary = dict(zip_iterator)

'5'

Ahora realizaremos los reemplazamientos. 
Los primeros dos los hemos hecho a mano a moodo de ilustrar como funciona el reemplazamiento, los últimos dos, los hemos hecho utilizando la lista que hemos creado.

In [27]:
### df_nulls['v_year'] = df_nulls['v_year'].astype(int)
#Reemplazamos los distintos meses para que sean todos iguales ya que algunos tienne un formato como 01,02 o algunos son int
data['c_mnth']=data['c_mnth'].replace({'01':'1','02':'2',1:'1',2:'2',3:'3',4:'4',5:'5',6:'6',7:'7',8:'8',9:'9',10:'10',11:'11',12:'12'})
#Reeemplazamos c_wday para que todos sean categoricos, ya que algunos son ints 
data['c_wday']=data['c_wday'].replace({'01':'1','02':'2',1:'1',2:'2',3:'3',4:'4',5:'5',6:'6',7:'7',8:'8',9:'9',10:'10',11:'11',12:'12'})
#Reemplazamos c_vehs
data['c_vehs']=data['c_vehs'].replace(diccionary)
#Reemplazamos c_conf
data['c_conf']=data['c_conf'].replace(diccionary)

In [28]:
#Visualizamos
data

,c_year,c_mnth,c_wday,c_hour,c_sev,c_vehs,c_conf,c_rcfg,c_wthr,c_rsur,c_raln,c_traf,v_id,v_type,v_year,p_id,p_sex,p_age,p_psn,p_isev,p_safe,p_user,acc_mortal
0,1999,1,1,20,2,2,34,UU,1,5,3,03,01,06,1990,01,M,41,11,1,UU,1,0
1,1999,1,1,20,2,2,34,UU,1,5,3,03,02,01,1987,01,M,19,11,1,UU,1,0
2,1999,1,1,20,2,2,34,UU,1,5,3,03,02,01,1987,02,F,20,13,2,02,2,0
3,1999,1,1,08,2,1,1,UU,5,3,6,18,01,01,1986,01,M,46,11,1,UU,1,0
4,1999,1,1,08,2,1,1,UU,5,3,6,18,99,NN,-99,01,M,05,99,2,UU,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5860400,2014,UU,U,UU,2,UU,UU,01,U,U,U,UU,13,07,0,01,M,24,11,1,NN,1,0
5860401,2014,UU,U,23,2,1,6,05,1,1,U,18,1,14,2006,01,M,29,96,2,09,5,0
5860402,2014,UU,U,14,2,1,2,01,1,5,4,18,1,01,2006,01,F,UU,11,2,01,1,0
5860403,2014,UU,U,22,1,1,6,01,2,4,Q,18,1,22,0,01,M,67,12,3,01,U,1
5860404,2014,UU,U,22,1,1,6,01,2,4,Q,18,1,22,0,02,M,10,98,1,01,U,1

### Quitamos variables que no utilizaremos

Quitaremos variables que no podemos usar ya que no las tendremos al momento de tener el modelo en producción o porque no aportan valor. 

Las variables que no utilizaremos son:
- el id del vehículo
- el id de la persona
- la c_sev ya que utilizaremos 'acc_moral' que es nuestra 1, es nuestra variable target
- La variable p_isev que signfica si ha tenido tratamiento médico o si ha muerto, con lo cual es información que no tendremos cuando se ponga en producción el modelo

In [29]:
#Quitamos la variable v_id, p_id, c_sev y p_isev ya que es info que no tendremos cuando suceda el accidente o que no aportan valor. 
data=data.drop(['v_id','p_id','c_sev','p_isev'],axis=1)

### Enconding

Utilizaremos encodings para poder pasar a los modelos nuestras variables categóricas.

La forma de tratar las varibles es hacer que las variables cíclicas como el mes, el día de la semana y la hora sean cofificadas usando el OneHotEncoder y las demás variables utilizaremos el CatBoost.

In [38]:
#defnimos columnas para crear dos data frames en base al tipo de encoder que vamos a usar para cada columna

ohe_columns=['c_mnth','c_wday','c_hour']
catboost_columns=['c_vehs','p_age','v_year','c_year','c_conf','c_rcfg','c_wthr','c_rsur','c_raln','c_traf','v_type','p_sex','p_psn','p_safe','p_user']
to_be_ingnored= ['v_year','c_year','acc_mortal']

In [32]:
#definimos dos data frames para dos encoders distintos
ohe_df=data[ohe_columns]
cat_df=data[catboost_columns]

In [33]:
ohc = OneHotEncoder()

In [34]:
# Hacemos un loop para transformar nuestras variables a OneHot
for c in ohe_columns:
    
    ohe= ohc.fit_transform(ohe_df[c].values.reshape(-1,1)).toarray()
    dfOneHot=pd.DataFrame(ohe,columns = [c+str(ohc.categories_[0][i]) 
                                         for i in range(len(ohc.categories_[0]))]).set_index(ohe_df.index)
    ohe_df=pd.concat([ohe_df,dfOneHot],axis=1)
ohe_df

,c_mnth,c_wday,c_hour,c_mnth1,c_mnth10,c_mnth11,c_mnth12,c_mnth2,c_mnth3,c_mnth4,c_mnth5,c_mnth6,c_mnth7,c_mnth8,c_mnth9,c_mnthUU,c_wday1,c_wday2,c_wday3,c_wday4,c_wday5,c_wday6,c_wday7,c_wdayU,c_hour00,c_hour01,c_hour02,c_hour03,c_hour04,c_hour05,c_hour06,c_hour07,c_hour08,c_hour09,c_hour10,c_hour11,c_hour12,c_hour13,c_hour14,c_hour15,c_hour16,c_hour17,c_hour18,c_hour19,c_hour20,c_hour21,c_hour22,c_hour23,c_hourUU
0,1,1,20,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,1,1,20,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,1,1,20,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,1,1,08,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,1,08,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5860400,UU,U,UU,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5860401,UU,U,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5860402,UU,U,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5860403,UU,U,22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5860404,UU,U,22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [35]:
#Quitamos las columnas originales del dataframe
ohe_df=ohe_df.drop(ohe_columns,axis=1)

In [36]:
#Visualizamos el dataframe
ohe_df

,c_mnth1,c_mnth10,c_mnth11,c_mnth12,c_mnth2,c_mnth3,c_mnth4,c_mnth5,c_mnth6,c_mnth7,c_mnth8,c_mnth9,c_mnthUU,c_wday1,c_wday2,c_wday3,c_wday4,c_wday5,c_wday6,c_wday7,c_wdayU,c_hour00,c_hour01,c_hour02,c_hour03,c_hour04,c_hour05,c_hour06,c_hour07,c_hour08,c_hour09,c_hour10,c_hour11,c_hour12,c_hour13,c_hour14,c_hour15,c_hour16,c_hour17,c_hour18,c_hour19,c_hour20,c_hour21,c_hour22,c_hour23,c_hourUU
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5860400,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5860401,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5860402,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5860403,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5860404,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [37]:
#Ahora haremos CatboostEncoder para las variables correspondientes

for i in catboost_columns:

    cbe = ce.cat_boost.CatBoostEncoder(cols=i)
    cat_df[i] = cbe.fit_transform(cat_df[i],cat_df['acc_mortal'])

cat_df

,c_vehs,p_age,acc_mortal,v_year,c_year,c_conf,c_rcfg,c_wthr,c_rsur,c_raln,c_traf,v_type,p_sex,p_psn,p_safe,p_user
0,0.016842,0.016842,0,0.016842,0.016842,0.016842,0.016842,0.016842,0.016842,0.016842,0.016842,0.016842,0.016842,0.016842,0.016842,0.016842
1,0.008421,0.016842,0,0.016842,0.008421,0.008421,0.008421,0.008421,0.008421,0.008421,0.008421,0.016842,0.008421,0.008421,0.008421,0.008421
2,0.005614,0.016842,0,0.008421,0.005614,0.005614,0.005614,0.005614,0.005614,0.005614,0.005614,0.008421,0.016842,0.016842,0.016842,0.016842
3,0.016842,0.016842,0,0.016842,0.004211,0.016842,0.004211,0.016842,0.016842,0.016842,0.016842,0.005614,0.005614,0.005614,0.005614,0.005614
4,0.008421,0.016842,0,0.016842,0.003368,0.008421,0.003368,0.008421,0.008421,0.008421,0.008421,0.016842,0.004211,0.016842,0.004211,0.016842
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5860400,0.029606,0.016622,0,0.015648,0.015125,0.014146,0.027775,0.008903,0.010226,0.007496,0.014393,0.037189,0.020534,0.014579,0.014368,0.014215
5860401,0.028631,0.015792,0,0.015352,0.015125,0.025446,0.022709,0.015984,0.016924,0.007496,0.024133,0.030037,0.020534,0.048236,0.030242,0.030037
5860402,0.028631,0.010018,0,0.015352,0.015125,0.024646,0.027775,0.015984,0.018749,0.040346,0.024133,0.014285,0.012579,0.014579,0.081154,0.014215
5860403,0.028631,0.020549,1,0.015648,0.015125,0.025446,0.027775,0.020858,0.021547,0.010177,0.024133,0.070325,0.020534,0.020585,0.081153,0.024559
5860404,0.028632,0.016180,1,0.015651,0.015128,0.025448,0.027775,0.020859,0.021560,0.010211,0.024134,0.070528,0.020534,0.028389,0.081158,0.024565

In [39]:
#Unimos los datasets
df_models=pd.concat([ohe_df, cat_df], axis=1)

In [40]:
#Visualizamos nuestro dataframe
df_models

,c_mnth1,c_mnth10,c_mnth11,c_mnth12,c_mnth2,c_mnth3,c_mnth4,c_mnth5,c_mnth6,c_mnth7,c_mnth8,c_mnth9,c_mnthUU,c_wday1,c_wday2,c_wday3,c_wday4,c_wday5,c_wday6,c_wday7,c_wdayU,c_hour00,c_hour01,c_hour02,c_hour03,c_hour04,c_hour05,c_hour06,c_hour07,c_hour08,c_hour09,c_hour10,c_hour11,c_hour12,c_hour13,c_hour14,c_hour15,c_hour16,c_hour17,c_hour18,c_hour19,c_hour20,c_hour21,c_hour22,c_hour23,c_hourUU,c_vehs,p_age,acc_mortal,v_year,c_year,c_conf,c_rcfg,c_wthr,c_rsur,c_raln,c_traf,v_type,p_sex,p_psn,p_safe,p_user
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.016842,0.016842,0,0.016842,0.016842,0.016842,0.016842,0.016842,0.016842,0.016842,0.016842,0.016842,0.016842,0.016842,0.016842,0.016842
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.008421,0.016842,0,0.016842,0.008421,0.008421,0.008421,0.008421,0.008421,0.008421,0.008421,0.016842,0.008421,0.008421,0.008421,0.008421
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.005614,0.016842,0,0.008421,0.005614,0.005614,0.005614,0.005614,0.005614,0.005614,0.005614,0.008421,0.016842,0.016842,0.016842,0.016842
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.016842,0.016842,0,0.016842,0.004211,0.016842,0.004211,0.016842,0.016842,0.016842,0.016842,0.005614,0.005614,0.005614,0.005614,0.005614
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.008421,0.016842,0,0.016842,0.003368,0.008421,0.003368,0.008421,0.008421,0.008421,0.008421,0.016842,0.004211,0.016842,0.004211,0.016842
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5860400,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.029606,0.016622,0,0.015648,0.015125,0.014146,0.027775,0.008903,0.010226,0.007496,0.014393,0.037189,0.020534,0.014579,0.014368,0.014215
5860401,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.028631,0.015792,0,0.015352,0.015125,0.025446,0.022709,0.015984,0.016924,0.007496,0.024133,0.030037,0.020534,0.048236,0.030242,0.030037
5860402,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.028631,0.010018,0,0.015352,0.015125,0.024646,0.027775,0.015984,0.018749,0.040346,0.024133,0.014285,0.012579,0.014579,0.081154,0.014215
5860403,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.028631,0.020549,1,0.015648,0.015125,0.025446,0.027775,0.020858,0.021547,0.010177,0.024133,0.070325,0.020534,0.020585,0.081153,0.024559
5860404,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.028632,0.016180,1,0.015651,0.015128,0.025448,0.027775,0.020859,0.021560,0.010211,0.024134,0.070528,0.020534,0.028389,0.081158,0.024565

In [ ]:
#df_models.to_csv(path_or_buf="../data/df_models")

In [41]:
#Definimos las X y las Ys
X=df_models.drop('acc_mortal',axis=1)
y=df_models.acc_mortal

In [42]:
#Guardamos el dataset 
#X.to_parquet("../data/X")

In [43]:
#Guardamos el dataset
#y.to_csv("../data/y")

### Split de Train y Test
Haremos un split estratificado, debido a que tenemos un dataset muy desbalanceado

In [66]:
%%time
#split entre train y test
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.20,random_state=0,stratify=y)

CPU times: user 10.1 s, sys: 4.97 s, total: 15.1 s
Wall time: 17.2 s

In [67]:
#Guardamos los datos
'''X_train.to_parquet("../data/X_train")
X_test.to_parquet("../data/X_test")
y_train.to_csv("../data/y_train")
y_test.to_csv("../data/y_test")'''